# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_auto_20180610_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookkeeping.RealTransactionSource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6),
        ),
    ]
