# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0015_auto_20180612_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookkeeping.RealTransactionSource'),
        ),
    ]
