# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 15:24
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

from django.db import migrations, models
import django.db.models.deletion

def create_default_accounts(apps, schema_editor):
    from byro.bookkeeping.models import AccountCategory
    Account = apps.get_model("bookkeeping", "Account")
    Configuration = apps.get_model('common', 'Configuration')
    config, _ignore = Configuration.objects.get_or_create()
    if not config.fees_account:
        fees_account, _ignore = Account.objects.get_or_create(
            name=_("Member fees"),
            account_category=AccountCategory.INCOME,
        )
        config.fees_account = fees_account
    if not config.donations_account:
        donations_account, _ignore = Account.objects.get_or_create(
            name=_("Donations"),
            account_category=AccountCategory.INCOME,
        )
        config.donations_account = donations_account
    if not config.fees_receivable_account:
        fees_receivable_account, _ignore = Account.objects.get_or_create(
            name=_("Member fees receivable"),
            account_category=AccountCategory.ASSET,
        )
        config.fees_receivable_account = fees_receivable_account
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0013_auto_20180609_1258'),
        ('common', '0009_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='fees_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='donations_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fees_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookkeeping.Account'),
        ),
        migrations.RunPython(create_default_accounts, migrations.RunPython.noop),
    ]
